//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Programming.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FPL_INPUT_COIL
    {
        public int COIL_NO { get; set; }
        public string JOB_ID { get; set; }
        public string COIL_ID { get; set; }
        public int COIL_SEQ { get; set; }
        public string COMBINATION_ID { get; set; }
        public string HEAT_ID { get; set; }
        public string LOT_ID { get; set; }
        public string COIL_CODE { get; set; }
        public string LEVEL3_ID { get; set; }
        public Nullable<System.DateTime> HEAT_DATE { get; set; }
        public decimal WIDTH { get; set; }
        public decimal AIMING_WIDTH { get; set; }
        public decimal ACTUAL_WIDTH { get; set; }
        public decimal THICKNESS { get; set; }
        public decimal AIMING_THICKNESS { get; set; }
        public decimal ACTUAL_THICKNESS { get; set; }
        public decimal LENGTH { get; set; }
        public decimal WEIGHT { get; set; }
        public decimal EXTERNAL_DIAMETER { get; set; }
        public decimal INTERNAL_DIAMETER { get; set; }
        public decimal DOWNCOIL_TEMPERATURE { get; set; }
        public string MATERIAL_GRADE_ID { get; set; }
        public int YIELD_STRENGTH { get; set; }
        public int TENSILE_STRENGTH { get; set; }
        public decimal ELONGATION { get; set; }
        public int ALLOY_CODE { get; set; }
        public string TREATMENT_CODE { get; set; }
        public int HEAD_CUT_MODE { get; set; }
        public decimal MIN_HEAD_SCRAP_LENGTH { get; set; }
        public decimal MIN_HEAD_SCRAP_THK { get; set; }
        public decimal MAX_HEAD_SCRAP_THK { get; set; }
        public int TAIL_CUT_MODE { get; set; }
        public decimal MIN_TAIL_SCRAP_LENGTH { get; set; }
        public decimal MIN_TAIL_SCRAP_THK { get; set; }
        public decimal MAX_TAIL_SCRAP_THK { get; set; }
        public decimal ENTRY_CROWN { get; set; }
        public string SOURCE { get; set; }
        public Nullable<int> SOURCE_CODE_ID { get; set; }
        public int DEFECTS_NUM { get; set; }
        public int SADDLE_NUM { get; set; }
        public int SPOOL_MODE { get; set; }
        public int SEPARATOR_MODE { get; set; }
        public int UNCOIL_DIRECTION { get; set; }
        public Nullable<System.DateTime> ORDER_DUE_DATE { get; set; }
        public int CHANGE_SEQ_REASON { get; set; }
        public int CHANGE_SEQ_COUNT { get; set; }
        public string INFO_DESCRIPTION { get; set; }
        public string INFO_PRODUCT { get; set; }
        public Nullable<int> INFO_PRODUCTION_CODE { get; set; }
        public string INFO_SAMPLE { get; set; }
        public int ROLLING_COUNT { get; set; }
        public int ROLLING_TYPE { get; set; }
        public int REWORK_COIL_FLAG { get; set; }
        public string REWORK_COIL_TYPE { get; set; }
        public string STORAGE_LOCATION { get; set; }
        public int STORAGE_STATUS { get; set; }
        public string STORAGE_DESTINATION { get; set; }
        public decimal ANNEALING_THICKNESS { get; set; }
        public string OPER_CODE { get; set; }
        public decimal OPER_EN_WIDTH { get; set; }
        public decimal OPER_EN_THICKNESS { get; set; }
        public string SUPPLIER_ID { get; set; }
        public int PDI_ERROR_FLAG { get; set; }
        public int DUMMY_COIL_FLAG { get; set; }
        public int REPAIR_FLAG { get; set; }
        public string REPAIR_TYPE { get; set; }
        public string INSPECTION_CODE { get; set; }
        public string INSPECTION_GRADE { get; set; }
        public int OPERATION_CODE { get; set; }
        public string OPERATION_NAME { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public string L3_COMBINATION_ID { get; set; }
        public int SEQ_IN_COMBINATION { get; set; }
        public int COMBINATION_FLAG { get; set; }
        public int STATUS { get; set; }
        public string REMARK { get; set; }
        public string OPERATOR { get; set; }
        public Nullable<System.DateTime> REVISION { get; set; }
        public int DUMMY_COIL_COUNT { get; set; }
        public decimal SPOOL_THICKNESS { get; set; }
        public decimal MAX_ENTRY_TENS { get; set; }
        public string MATERIAL_QUALITY { get; set; }
        public int FINISHED_PRODUCT { get; set; }
        public string FINAL_PRODUCT_CODE { get; set; }
        public string FINAL_PRODUCT_QUALITY { get; set; }
        public int REJECTED_COIL_COUNT { get; set; }
        public string LABEL_REMARK { get; set; }
        public decimal COILING_TENSION { get; set; }
        public decimal ALLOY_FACTOR { get; set; }
        public int ACTUAL_WR_FAMILY_NO { get; set; }
        public decimal TARGET_ROUGHNESS { get; set; }
    }
}
